### ISSUE TITLE
Example : self_authentication - Intermittently hangs

### ISSUE THREAD

**Issue by rossmuir** [maidsafe/safe_client#146]
The example : self_authentication - Intermittently hangs at `Trying to log in ...` when incorrect credentials are passed.
```
user@machine:~/SAFENetwork_examples$ ./self_authentication

Do you already have an account created (enter Y for yes) ?
N

	Account Creation
	================

------------ Enter Keyword ---------------
ross


------------ Enter Password --------------
ross


--------- Enter PIN (4 Digits) -----------
1234

Trying to create an account ...
Account Created Successfully !!


	Auto Account Login
	==================

Trying to log into the created account using supplied credentials ...
Account Login Successful !!


	Manual Account Login
	====================

------------ Enter Keyword ---------------
ross


------------ Enter Password --------------
ross


--------- Enter PIN (4 Digits) -----------
4321

Trying to log in ...


```

Expect to see `Account Login Failed !! Reason: ClientError::SymmetricDecipherFailure`

**Comment by ustulation** [comment]
Nope .. The behavior is epected .. this is not the case of `SymmetricDecipherFailure`. Explanation:
<1> Keyword and Key generate the user id .. and this is the location of session packet on the network
<2> Password and Key generate crypto-keys which if wrong will result in `SymmetricDecipherFailure`

The problem is Pin appears in both above. So when you give the wrong PIN, the user id generated is wrong, hence the session packet is not found in the network. The Symmetric Decipher only happens once you fetch the packet. If the fetching itself fails, it is due to an invalid GET and invalid getters are treated as hackers and nothing is returned to them so the wait is infinite.

This behavior is **not** intermittent .. it should be consistent. You will get symmetric decipher error if only the password is wrong since the correct Keyword and PIN will have fetched the session packet.

The timeouts etc need to be built in the application using these Client modules (no timer operations in maidsafe client modules should be there - at-least according to me - the flexibility is with app - devs to do what they want to do)
 
So issue reported is expected.

**Comment by rossmuir** [comment]
Ok and thanks for the explanation.
